#:schema https://docs.jj-vcs.dev/latest/config-schema.json
[user]
name = "Charlotte Smith"
email = "charliesmith5019@gmail.com"

[ui]
default-command = "log"
diff-formatter = ["difft", "--color=always", "$left", "$right"]

[aliases.with-delta]
definition = [
    "--config",
    "ui.pager=\"delta --features=catppuccin-mocha --side-by-side --line-numbers\"",
    "--config",
    "ui.diff-formatter=\":git\"",
]

[aliases.diff-delta]
definition = ["with-delta", "diff"]
doc = "Render diff with delta"

[aliases.show-delta]
definition = ["with-delta", "show"]
doc = "Render show with delta"

[revset-aliases."closest_pushable(to)"]
definition = 'heads(::to & mutable() & ~empty() & description(regex:".+"))'
doc = "Closest mutable, non-empty, described commits at or behind to"

[revsets]
bookmark-advance-to = "closest_pushable(@)"

[template-aliases]
"slugify(str)" = '''
  truncate_end(
    65,
    str.first_line()
      .replace(regex:'[^[[:alnum:]].]', '-')
      .replace(regex:'-{2,}', '-')
      .replace(regex:'\.{2,}', '.')
      .replace(regex:'(^-+|-+$)', '')
      .lower()
  )
'''

[templates]
git_push_bookmark = 'slugify(description) ++ "/" ++ change_id.short()'

[git]
# Prevent pushing work in progress or anything explicitly labeled "private"
private-commits = "description('wip:*') | description('private:*')"
