[aliases.ba]
definition = ["bookmark", "advance"]
doc = "Alias for 'bookmark advance'"

[aliases.bap]
definition = ["util", "exec", "--", "bash", "-c", """
jj bookmark advance
jj git push
"""]
doc = "Advance bookmark and push"

[aliases.bc]
definition = ["bookmark", "create"]
doc = "Alias for 'bookmark create'"

[aliases.l]
definition = ["log", "-r", "::@"]
doc = "Show full tree log"

[aliases.lf]
definition = ["log", "-r", "::"]
doc = "Show full log"

[aliases.fetch]
definition = ["git", "fetch"]
doc = "Alias for 'git fetch'"

[aliases.push]
definition = ["git", "push"]
doc = "Alias for 'git push'"

[revset-aliases]
"mutable_roots()" = "roots(trunk()..) & mutable()"

[aliases]
restack = ["rebase", "-o", "trunk()", "-s", "mutable_roots()"]

[aliases.update]
definition = ["util", "exec", "--", "bash", "-c", """
jj git fetch 

trunk_name=$(jj log -r 'trunk()' -T 'local_bookmarks ++ "\n"' --no-graph | head -n1)
branches=$(jj log -r 'mutable_roots()' --no-graph -T 'change_id ++ "\n"')
echo "jj: Rebasing $(echo "$branches" | wc -l) branches onto ${trunk_name}..."

jj rebase -o 'trunk()' -s 'mutable_roots()'
"""]
doc = "Fetches remote state, then rebases descendants onto root commit"

[aliases.clean]
definition = ["util", "exec", "--", "git", "clean", "-e", ".jj/"]
doc = "Like `git clean` but ignores `.jj/` directory"
